# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_util', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Animer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_util', models.CharField(max_length=50)),
                ('diplome_appr', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lib_categ', models.CharField(max_length=200)),
                ('administrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Administrateur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lib_chap', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lib_cour', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_formation', models.CharField(max_length=80)),
                ('type_formation', models.CharField(max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lib_form', models.CharField(max_length=80)),
                ('date_deb_form', models.DateField()),
                ('date_fin_form', models.DateField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Categorie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Regroupement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date_group', models.DateField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Formation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lib_ress', models.CharField(max_length=80)),
                ('type_ress', models.CharField(max_length=50)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Chapitre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date_test', models.DateField()),
                ('note_test', models.IntegerField()),
                ('id_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Formation')),
                ('id_util', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Apprenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Formation'),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Cours'),
        ),
        migrations.AddField(
            model_name='apprenant',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Formation'),
        ),
        migrations.AddField(
            model_name='apprenant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animer',
            name='id_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Formation'),
        ),
        migrations.AddField(
            model_name='animer',
            name='id_util',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Formateur'),
        ),
    ]
