# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 11:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='docfile',
            field=models.FileField(default=datetime.datetime(2016, 4, 10, 11, 44, 50, 706863, tzinfo=utc), upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
